### ISSUE TITLE
issue with yarn build

### ISSUE THREAD

**Issue by nullkatar** [erksch/waymo-open-dataset-viewer#20]
Hello @erksch ! Thank you very much for your work! Unfortunately I'm having difficulties with running your visualizer tool, the problem is that if I call "yarn build" it gives me the following (see screenshot). Is there any chance for me to make it work? 
![image](https://user-images.githubusercontent.com/27498544/128860660-37399a1e-8251-4ffb-8f8c-708a423e3cfb.png)

**Comment by erksch** [comment]
Maybe this happened when updating three.js carelessly, you can try to revert it back to 0.111.0 in the `package.json`

**Comment by erksch** [comment]
Indeed https://github.com/mrdoob/three.js/releases/tag/r117:
> Rename maxInstancedCount to instanceCount. #19135 (@WestLangley)

**Comment by nullkatar** [comment]
Yep, than truly works! Thanks a lot @erksch
