### ISSUE TITLE
Perspective control

### ISSUE THREAD

**Issue by BenQLange** [erksch/waymo-open-dataset-viewer#3]
Hi,
Thanks for the viewer!! It is super useful.
One thing that I find slightly unintuitive/would consider changing is the spatial control of camera/our view perspective.

Thanks,
Bernard

**Comment by erksch** [comment]
Hey! Glad you like it :)
Yeah, I am using the orbit controls of threejs which are a little bit unintuitive.

But I am planning a bigger update of the viewer so maybe I could add improvements to the camera, too.

**Comment by BenQLange** [comment]
Great! I am looking forward to the update.

**Comment by P-Light** [comment]
Will be any updates?
