### ISSUE TITLE
The tools you use to show point cloud and plot bbox

### ISSUE THREAD

**Issue by jiangzhengkai** [erksch/waymo-open-dataset-viewer#4]
Hi, @erksch First, Thanks for your great work.

I would like to know what tool you use to show point cloud and label, like open3d, pcl

**Comment by erksch** [comment]
Hey, thanks for checking by!

Although I know there are some fancy ways of rendering point clouds like Caesium and PCL, I am using no specific tools besides WebGL and ThreeJS with some tweaks for better performance. I think that is good enough as long nobody has serious performance problems :)

**Comment by erksch** [comment]
I'll close this, feel free to ask more questions :D
