### ISSUE TITLE
Some points are still visible even if all LIDARs are diabled

### ISSUE THREAD

**Issue by Nuri-benbarka** [erksch/waymo-open-dataset-viewer#5]
Hi,
I like this viewer it is simple and convenient, thanks for the great work. I would like to ask a question If you see the attached image 
![Screenshot from 2020-04-25 11-16-07](https://user-images.githubusercontent.com/60135952/80276121-b5dd4a00-86e6-11ea-80ce-e3b43f3e14b1.png)
there are some points still visible although I disabled all of the LIDARs, do you have an explination for this?

**Comment by erksch** [comment]
I guess that can happen.
Here is a snippet from the [dataset.proto](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto):
```
message LaserName {
  enum Name {
    UNKNOWN = 0;
    TOP = 1;
    FRONT = 2;
    SIDE_LEFT = 3;
    SIDE_RIGHT = 4;
    REAR = 5;
  }
}
```
You can see points can indeed have no associated laser.

**Comment by Nuri-benbarka** [comment]
that's interesting, I wonder where are these points coming from. I will ask in the waymo_dataset repo. can you add a botton to also toggle these unknown points?

**Comment by erksch** [comment]
That's a good idea!

**Comment by erksch** [comment]
Closing :)
