### ISSUE TITLE
Shift between the main LIDAR and the rest

### ISSUE THREAD

**Issue by Nuri-benbarka** [erksch/waymo-open-dataset-viewer#6]
Hi,
I am checking the visualizations, and sometimes there is a misorientation between main LIDAR and the rest as shown in this image:
![Screenshot from 2020-04-25 11-47-18](https://user-images.githubusercontent.com/60135952/80276726-cbed0980-86ea-11ea-9fb3-582f7cf99cf0.png)
here the main road is shown twice(from north to south and east to west). How can one solve this problem?

**Comment by erksch** [comment]
Oh yeah, I had the same problem when running the websocket with a GPU that has little RAM (2GB). Then something messes up when converting the range images. Does this apply to your setup?

**Comment by Nuri-benbarka** [comment]
I have a GeForce RTX 2060, which has a 6GB RAM. I can try with another GPU and tell you what happens.

**Comment by erksch** [comment]
Wait a minute and I'll give you some code to disable the gpu when running the websocket.

**Comment by erksch** [comment]
Try add this at the top of the websocket file:
`os.environ['CUDA_VISIBLE_DEVICES'] = -1`
to disable using cuda for the processing altogether.
I never had problems with running it on the CPU and it is just as fast.

**Comment by Nuri-benbarka** [comment]
I run the code using the CPU and it is working fine. 
Many thanks for fast support on a Saturday morning.
I suggest updating the README to warn users about this issue

**Comment by erksch** [comment]
Yes, you're right, I initially thought this problem is due to my super whack GPU with 2 GB but when your RTX is not doing it seems to be a general problem.
